"""
Pydantic schemas for API request/response models
"""
from app.schemas.chat import (
    ChatMessage,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ModelInfo,
    ToolCall as ToolCallSchema,
    ToolResult as ToolResultSchema,
    ToolDefinition,
    FunctionDefinition,
    ChatCompletionChoice,
    Usage,
    ChatCompletionChunk,
    ChunkChoice,
    ChatMessageDelta,
)
from app.schemas.api import (
    SessionCreate,
    SessionUpdate,
    SessionResponse,
    SessionListResponse,
    MessageCreate,
    MessageResponse,
    MessageListResponse,
    ProviderCreate,
    ProviderUpdate,
    ProviderResponse,
    ProviderListResponse,
    GlobalConfigUpdate,
    GlobalConfigResponse,
    ChatRequest,
    HealthResponse,
    SSEEvent,
    ContentDeltaEvent,
    ToolCallStartEvent,
    ToolCallEndEvent,
    DoneEvent,
    ErrorEvent,
)

__all__ = [
    # Chat schemas
    "ChatMessage",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ModelInfo",
    "ToolCallSchema",
    "ToolResultSchema",
    "ToolDefinition",
    "FunctionDefinition",
    "ChatCompletionChoice",
    "Usage",
    "ChatCompletionChunk",
    "ChunkChoice",
    "ChatMessageDelta",
    # API schemas
    "SessionCreate",
    "SessionUpdate",
    "SessionResponse",
    "SessionListResponse",
    "MessageCreate",
    "MessageResponse",
    "MessageListResponse",
    "ProviderCreate",
    "ProviderUpdate",
    "ProviderResponse",
    "ProviderListResponse",
    "GlobalConfigUpdate",
    "GlobalConfigResponse",
    "ChatRequest",
    "HealthResponse",
    "SSEEvent",
    "ContentDeltaEvent",
    "ToolCallStartEvent",
    "ToolCallEndEvent",
    "DoneEvent",
    "ErrorEvent",
]
